### ISSUE TITLE
Application does not work anymore, needs to update Enum selectors

### ISSUE THREAD

**Issue by Jean1dev** [JFCodes/WhatsAppJS#3]
WhatsApp FE structure/classes has been changed, need update _constants.ts
`export enum Selectors {
    'QRCODE_IMG_PARENT_CLASS' = '._2EZ_m',
    'CONVERSATIONS_PARENT_CLASS' = '._1c8mz',
    'CONVERSATION_PLACEHOLDER_ELEMENT' = '._1AKfk',
    'CONVERSATION_MESSAGE_RESULTS_ELEMENT' = '._34xP_',
    'CONVERSATION_TARGET_ELEMENT' = '._2xINO',
    'CONVERSATION_SEARCH_INPUT_ELEMENT' = '._2zCfw',
    'CONVERSATION_CLEAR_SEARCH' = '._3Burg',
    'CHAT_MESSAGE_FIELD_SELECTOR' = '._2S1VP',
    'CHAT_SEND_BUTTON_SELECTOR' = '._35EW6'
}`

**Comment by JFCodes** [comment]
After a long time I am picking this one up again.
Removing outdated issues.
